# Generated by Django 5.0.6 on 2024-05-23 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_detail_supplier_supplierpart_detail_suppliers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplierpart',
            old_name='part',
            new_name='detail',
        ),
    ]
