# Generated by Django 5.0.6 on 2024-05-23 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_detail_price_supplierpart_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SupplierPart',
            new_name='SupplierDetail',
        ),
    ]
