# Generated by Django 5.0.6 on 2024-05-23 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_items', to='shop.detail')),
            ],
        ),
    ]
