# Generated by Django 5.0.6 on 2024-05-24 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_remove_employee_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'permissions': [('employee', 'Can view suppliers list')]},
        ),
    ]
