# Generated by Django 5.0.6 on 2024-05-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_employee_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
