# Generated by Django 5.0.6 on 2024-05-24 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_location_storeorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeorder',
            name='promo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='store_orders', to='shop.promocode'),
            preserve_default=False,
        ),
    ]
