# Generated by Django 5.0.6 on 2024-05-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_atricle_detail_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='price',
        ),
        migrations.AddField(
            model_name='supplierpart',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
