# Generated by Django 5.0.6 on 2024-05-24 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone_number',
        ),
    ]
