# Generated by Django 5.0.6 on 2024-05-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_companyinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default='bob.jpg', upload_to='articles/'),
            preserve_default=False,
        ),
    ]
